### ISSUE TITLE
Setting theme and its settings via vim.g and vim.cmd

### ISSUE THREAD

**Issue by ysomad** [aktersnurra/no-clown-fiesta.nvim#10]
Now it's required to use setup function as config in packer but it would be great to be able setting up the theme and its settings via `vim.g`.

What I mean by "use setup function as config"

```lua
use {
      'aktersnurra/no-clown-fiesta.nvim',
      config = function()
        require("no-clown-fiesta").setup({})
      end
}
```

Would be great to be able:
```lua
vim.cmd("colorscheme no-clown-fiesta") -- set theme
vim.g.noclownfiesta_type = "bold,italic" -- and other settings in similar way
```

Why? If someone wants to change theme, they need to remove dependency from packer and re-compile.

**Comment by aktersnurra** [comment]
Sounds good, I'll look into it.
