### ISSUE TITLE
LSP diagnosticts colors

### ISSUE THREAD

**Issue by ysomad** [aktersnurra/no-clown-fiesta.nvim#11]
In description said the theme has lsp support but LSP diagnostics errors in default color.

![image](https://user-images.githubusercontent.com/49870662/197833974-62f07d68-1cad-4ac7-bad1-c412505c2b69.png)

**Comment by aktersnurra** [comment]
Interesting, I'll try to update the highlight groups. What plugin displays the inline error? I use vim diagnostics and don't see the colors you display here.

**Comment by ysomad** [comment]
> Interesting, I'll try to update the highlight groups. What plugin displays the inline error? I use vim diagnostics and don't see the colors you display here.

I'm using vim diagnostics too

**Comment by aktersnurra** [comment]
I updated the lsp groups now. If it does not work now, you will have to figure out which groups it is since I don't see this myself.

**Comment by ysomad** [comment]
> I updated the lsp groups now. If it does not work now, you will have to figure out which groups it is, since I don't see this myself.

now it looks good, thanks!
