### ISSUE TITLE
Weird status line symbols on particular actions

### ISSUE THREAD

**Issue by ysomad** [aktersnurra/no-clown-fiesta.nvim#14]
After the update there is weird symbols appeared in the status bar

Without theme: 
![image](https://user-images.githubusercontent.com/49870662/198847584-05c309e3-2753-4eef-a278-a76b562b7c42.png)

With the theme:
![image](https://user-images.githubusercontent.com/49870662/198847596-edafeb28-fdc9-497b-89dd-ac2811f9e67e.png)

**Comment by ysomad** [comment]
For status line I'm using lualine

**Comment by aktersnurra** [comment]
Yeah, it is annoying, it is because StatusLine = StatusLineNC. I'll fix it soon.

**Comment by aktersnurra** [comment]
I tested the latest commit now and it looks good for me. Let me know if it solved it for you as well.

**Comment by ysomad** [comment]
> I tested the latest commit now and it looks good for me. Let me know if it solved it for you as well.

yup, great job! Now it's lookin hella good
