### ISSUE TITLE
Colorscheme for terminals?

### ISSUE THREAD

**Issue by ceoshikhar** [aktersnurra/no-clown-fiesta.nvim#15]
Hey! I love this colorscheme for my NVIM and was curious if you have made colorscheme for terminals or will you be making it in the future? I am not much knowledgable on this matter but there are like 16 colors (8 bold, 8 normal) that are enough for a colorscheme on terminals like Alacritty, Mintty, etc. I would really love to use `no-clown-fiesta` for 3 things - NVIM, Terminal and VSCode(a port for this will be very appreciated too!).

Thanks!

**Comment by mjachi** [comment]
As it happens, I'm trying to put these together. Setting up my desktop again after frying a previous Gentoo install. I'll be using 

1. nvim
2. vscode as secondary
3. kitty

Having done one such conversion before, there is a lot of "you need to choose"; it'll never be perfect (even OP chose the colors used here at some point). I'm basing VSCode off of the already existing Nord Wave, which I feel is similar and just needs to be "darkened" and "yellowed" a bit. Note that you have access to the color palette in `lua/no-clown-fiesta/palette.lua`.

@aktersnurra could you can set up an org for us to maintain these ports as opposed to personal repos?

**Comment by ceoshikhar** [comment]
@mjachi hey man, you have no idea how much I would love to use this colorscheme everywhere that I can. It's just so "perfect". No distractions, just code. Please update here if you release a port for VSCode or Terminals.

I will try to use `lua/no-clown-fiesta/palette.lua` for my terminal.

**Comment by aktersnurra** [comment]
Really grateful to hear that you all enjoy it! 

@mjachi sure can. I take the liberty to invite you both so you can start contribute. :)

If you use a terminal emulator that support Xresources you can look [here](https://github.com/aktersnurra/dotfiles/blob/master/.config/x11/xresources) for inspiration.

**Comment by smartinellimarco** [comment]
Hello everyone! Are there any updates? I just tried the theme and would love to use it in kitty.

**Comment by mjachi** [comment]
@smartinellimarco see [here](https://github.com/no-clown-fiesta/no-clown-fiesta.kitty).

**Comment by windowsrefund** [comment]
Just wanted to jump in and say how much I love this nvim colorscheme!. As far as terminals, window managers, etc go, I personally think it works fantastic with several of the base16 themes like `classic-dark` or `grayscale-dark`

![Screenshot_2023-07-09_00-40-09](https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/512222/2d300407-8a09-4fc7-a9a2-26299eeb6a76)
