### ISSUE TITLE
Contrast difference in diagnostic colors

### ISSUE THREAD

**Issue by ajitid** [aktersnurra/no-clown-fiesta.nvim#16]
![image](https://user-images.githubusercontent.com/26769888/216756281-dae6b684-fb4a-438f-a096-59aa337f682b.png)

Errors have lowest contrast while the hints have the highest wrt to the background. Can we change them such that they have same contrast, preferably as subdued as the error's color?

The picture above has these colors:
- DiagnosticError `#ac4142`
- DiagnosticWarn `#f4bf75`
- DiagnosticInfo `#f4bf75`
- DiagnosticHint `#a5d6ff`

**Comment by aktersnurra** [comment]
Thanks for the suggestion, I see what you mean. I'll investigate this and update the palette.

**Comment by aktersnurra** [comment]
I updated the palette so that the info/warning and hint now has the same contrast as error.

**Comment by ajitid** [comment]
Thank you... and sorry :\

I looked at the new colors and I feel  they really do not go along well rest of the theme. I was wrong, and I now believe having colors as contrasting as original DiagnosticWarn (`#f4bf75`) gives better result. I'll make a personal clone of the theme and make changes there. Thanks anyway!

**Comment by aktersnurra** [comment]
No worries, I reverted the change, I'll experiment a bit more. But I see your point with the info and hint having higher contrast to the background than the error.
