### ISSUE TITLE
Alternates?

### ISSUE THREAD

**Issue by ajitid** [aktersnurra/no-clown-fiesta.nvim#2]
Wondering if you came across themes which achieve a look similar to no-clown-fiesta, and if so can you can tell them here? 

Like for example I quite like https://github.com/rsms/sublime-theme but it is Sublime only.

**Comment by aktersnurra** [comment]
I got inspired for all over the place really, so I can unfortunately not point you to any specific source.

However, if you want to experiment yourself, have a look at the `palette.lua` for colors, and then color configurations in `Treesitter.lua` and `highlights.lua`.
