### ISSUE TITLE
telescope not transparent

### ISSUE THREAD

**Issue by ysomad** [aktersnurra/no-clown-fiesta.nvim#20]
Is there any setting to make float windows transparent?

**Comment by aktersnurra** [comment]
I guess you already tried setting transparent to `true` and this is not the desired outcome? Because I guess this makes all windows transparent, and this is not what you want?

If that is not what you want, I can look at the documentation and add a field in the styles option. I'll do it sometime this week if I get the chance.

**Comment by ysomad** [comment]
yes, I did set transparent to true but when telescope is floating all windows aren't transparent

```lua
use {
    'aktersnurra/no-clown-fiesta.nvim',
    config = function()
      require('no-clown-fiesta').setup({
        transparent = true
      })

      vim.cmd.colorscheme('no-clown-fiesta')

      vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
      vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
    end
  }
```

![image](https://user-images.githubusercontent.com/49870662/235818182-fb116a92-d3a9-416c-8ece-c1b1cb435523.png)
![image](https://user-images.githubusercontent.com/49870662/235818198-cb4e1c73-c22f-4b4f-a8dc-129b3340a74f.png)

**Comment by aktersnurra** [comment]
Could you please test this?

```lua
use {
    'aktersnurra/no-clown-fiesta.nvim',
    config = function()
      require('no-clown-fiesta').setup({
        transparent = true
      })

      vim.cmd.colorscheme('no-clown-fiesta')

      vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
      vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
      vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = 'none' })
    end
  }
```

**Comment by ysomad** [comment]
> Could you please test this?
> 
> ```lua
> use {
>     'aktersnurra/no-clown-fiesta.nvim',
>     config = function()
>       require('no-clown-fiesta').setup({
>         transparent = true
>       })
> 
>       vim.cmd.colorscheme('no-clown-fiesta')
> 
>       vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
>       vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })
>       vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = 'none' })
>     end
>   }
> ```

same

**Comment by ysomad** [comment]
any updates on this?

**Comment by aktersnurra** [comment]
I tried to set NormalFloat and TelescopeNormal to transparent if enabled, like you have done. Let me know if it helped. I don't use terminals that support transparent mode, so I cannot test it atm.

**Comment by m-abrarhasan** [comment]
is there any update on this issue?
I am having a similar problem with both telescope and lsp-saga.

![Screenshot 2023-05-16 at 12 56 26 AM](https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/61474167/12978d36-701d-4f02-94e4-ff54ae5f5f63)

**Comment by aktersnurra** [comment]
> is there any update on this issue? I am having a similar problem with both telescope and lsp-saga.
> 
> ![Screenshot 2023-05-16 at 12 56 26 AM](https://user-images.githubusercontent.com/61474167/238448983-12978d36-701d-4f02-94e4-ff54ae5f5f63.png)

No, I have been to busy. Since I do not use transparent terminals, could you help me with testing setting `NormalNC` bg to `none` as well? I think that might work.

**Comment by m-abrarhasan** [comment]
> > is there any update on this issue? I am having a similar problem with both telescope and lsp-saga.
> > ![Screenshot 2023-05-16 at 12 56 26 AM](https://user-images.githubusercontent.com/61474167/238448983-12978d36-701d-4f02-94e4-ff54ae5f5f63.png)
> 
> No, I have been to busy. Since I do not use transparent terminals, could you help me with testing setting `NormalNC` bg to `none` as well? I think that might work.

Nope, Still not working.

**Comment by aktersnurra** [comment]
> > No, I have been to busy. Since I do not use transparent terminals, could you help me with testing setting `NormalNC` bg to `none` as well? I think that might work.
> 
> ~Nope, Still not working.~
> 
> UPDATE : Setting `NormalNC` to `NONE` did fix the problem. I was also able to fix lsp-saga! thanks! ![Screenshot 2023-05-19 at 2 01 57 AM](https://user-images.githubusercontent.com/61474167/239368889-cf2b65a6-fe27-448f-9435-30fc0a25f43a.png)

Wonderful, I will update the color scheme to set it automatically if transparent is enabled. Thanks for the help!
