### ISSUE TITLE
Invisible cursor in nvim terminal

### ISSUE THREAD

**Issue by ddbrierton** [aktersnurra/no-clown-fiesta.nvim#21]
Hi

First, thanks for making this wonderful theme. It’s beautiful.

I have only noticed one issue, and that is that if you open a terminal inside nvim, e.g. with `:terminal`, then the cursor is invisible. It definitely seems to be theme related as if I change theme to anything else the cursor immediately becomes visible.

If for any reason you can’t reproduce I’m happy to provide screenshots and configuration details. Just let me know anything you might need.

Thanks again for the theme (and its great name).

**Comment by aktersnurra** [comment]
Thanks, I'm glad you enjoy it. I have noticed this as well, but never got around to fixing it since I usually don't use the terminal inside nvim that often. But I'll have a look at it later today, it should be an easy fix.

**Comment by aktersnurra** [comment]
I have now updated term cursor color and I configured the cursor to be a white when in focus, and bg color when unfocused. Let me know if there is any issues or suggestions.

**Comment by ddbrierton** [comment]
Thank you! All is now good for me.
