### ISSUE TITLE
TODO: highlights

### ISSUE THREAD

**Issue by smartinellimarco** [aktersnurra/no-clown-fiesta.nvim#24]
Im experiencing an issue where TODO, FIXME, and other labels, are being grayed out after a second when a new buffer is opened.
Before:

<img width="192" alt="Captura de pantalla 2023-07-09 a la(s) 18 54 34" src="https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/15314838/24cd9618-d546-4095-a764-d625e77f6186">

After:
<img width="250" alt="Captura de pantalla 2023-07-09 a la(s) 18 53 10" src="https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/15314838/94e1b896-04d7-4fe8-a2dc-fcd1c891468d">

I tried adding the highlight:
`     ["@text.note"] = { fg = palette.red },`
to treesitter, but it did not work.
Any clues?

**Comment by smartinellimarco** [comment]
@aktersnurra Only treesitter:
```
-- Setup treesitter
require('nvim-treesitter.configs').setup({
  ensure_installed = 'all',
  highlight = {
    enable = true,
  },
  indent = {
    enable = true
  }
})
```
I tried disabling it with no effect.
By the way, Is there a way to know which highlight group is affecting a variable? I

**Comment by nekonhub** [comment]
Install [treesitter-playground](https://github.com/nvim-treesitter/playground) to see element names.
You may have both Treesitter and Regex highlighting enabled. Try this [video](https://www.youtube.com/watch?v=w7i4amO_zaE) from ThePrimeagen - the Treesitter installation section in particular from about 9.09 minutes. Its "rapid fire" delivery, and you may need to go over it a few times, but it helped me enormously switching from init.vim to lua based config.

**Comment by aktersnurra** [comment]
> @aktersnurra Only treesitter:
> 
> ```
> -- Setup treesitter
> require('nvim-treesitter.configs').setup({
>   ensure_installed = 'all',
>   highlight = {
>     enable = true,
>   },
>   indent = {
>     enable = true
>   }
> })
> ```
> 
> I tried disabling it with no effect.

Ok, I never experienced the before state, so I don't know how to help you. But maybe you could try out a plugin like this [one](https://github.com/folke/todo-comments.nvim).

**Comment by smartinellimarco** [comment]
I dont use many plugins but finally, after trying some combinations I found out that this is breaking it:
```
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate'
  },
  {
    'VonHeikemen/lsp-zero.nvim',
    branch = 'v2.x',
    dependencies = {

      -- LSP Management
      { 'neovim/nvim-lspconfig' },
      {
        'williamboman/mason.nvim',
        build = ':MasonUpdate'
      },
      { 'williamboman/mason-lspconfig.nvim' },

      -- Autocompletion
      { 'hrsh7th/nvim-cmp' },
      { 'hrsh7th/cmp-nvim-lsp' },
      { 'L3MON4D3/LuaSnip' },
      { 'saadparwaiz1/cmp_luasnip' },
      { 'rafamadriz/friendly-snippets' },
    }
  },
```

**Comment by smartinellimarco** [comment]
After trying out some combinations I found out that is is breaking it:
```
  {
    'VonHeikemen/lsp-zero.nvim',
    branch = 'v2.x',
    dependencies = {

      -- LSP Management
      { 'neovim/nvim-lspconfig' },
      {
        'williamboman/mason.nvim',
        build = ':MasonUpdate'
      },
      { 'williamboman/mason-lspconfig.nvim' },

      -- Autocompletion
      { 'hrsh7th/nvim-cmp' },
      { 'hrsh7th/cmp-nvim-lsp' },
      { 'L3MON4D3/LuaSnip' },
      { 'saadparwaiz1/cmp_luasnip' },
      { 'rafamadriz/friendly-snippets' },
    }
  },
```

**Comment by smartinellimarco** [comment]
For anyone else having this issue (and many more incorrect highlights), and are using lsp-zero, do not forget to disable semantic highlights:
```
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(_, bufnr)
  lsp.default_keymaps({
    buffer = bufnr,
    preserve_mappings = false
  })
end)

-- Disable semantic highlight groups to avoid conflicts with treesitter
lsp.set_server_config({
  on_init = function(client)
    client.server_capabilities.semanticTokensProvider = nil
  end,
})
```
