### ISSUE TITLE
Request: nvim-dap-ui

### ISSUE THREAD

**Issue by windowsrefund** [aktersnurra/no-clown-fiesta.nvim#25]
Love this colorscheme! Any chance of supporting [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui)?

**Comment by aktersnurra** [comment]
No, I do not use debuggers, so it is unlikely I will put in the work. But you could either find the highlight groups in the docs and set them in your config, or make a PR.

**Comment by ysomad** [comment]
I'll add support for it on my free time.
