### ISSUE TITLE
Preview image is broken in the readme file

### ISSUE THREAD

**Issue by Einenlum** [aktersnurra/no-clown-fiesta.nvim#26]
The [link](https://camo.githubusercontent.com/bc2e84ef5727be71e6066a588c842d608bf9e9f57cbd9eeca5f8601ed1d07a09/68747470733a2f2f677573746166727964686f6c6d2e78797a2f696d616765732f6e6f2d636c6f776e2d6669657374612d696e2d632e77656270) leads to a not found response.

**Comment by aktersnurra** [comment]
Thanks, I will fix it straight away.
