### ISSUE TITLE
Python keyword highlight

### ISSUE THREAD

**Issue by ostadsgo** [aktersnurra/no-clown-fiesta.nvim#32]
Hi, Love the color scheme
The problem is that some keywords like `import`,  `from`,  `try` and `except` highlighted with color `palette.red`.
How can I translate this command to the lua and use it in the color scheme.
`: hi! @exception.python guifg=#7e97ab`

![2024-01-07-22:11:33-screenshot](https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/19627826/e41afeeb-eae0-4dcb-819b-693281b57d60)

**Comment by aktersnurra** [comment]
Thanks! I see that you are using lazy, so you can define a custom config function when you load the colorscheme where you override the highlight groups, e.g.:

```lua
config = function()
  vim.api.nvim_set_hl(0, "@exeption.python", { fg = "#7e97ab" })
 end,
```

**Comment by ostadsgo** [comment]
Thanks, I solved my problem right after posting with `vim.cmd(""hi! @exception.python guifg=#7e97ab")` passing it to lazy `config` option. 
After the response, I add these lines to make it nicer. but I was thinking to add separate file for Python, like we have for `git` `treesitter` and etc. I  don't know how create hl group for something like `@exception.python`. If I had to change colors for different languages eventually I need to figure out how to create different group for groups that I `inspect` in neovim. 

```lua
    config = function()
      local palette = require("no-clown-fiesta.palette")
      vim.cmd("colorscheme no-clown-fiesta")
      vim.api.nvim_set_hl(0, "@exeption.python", { fg = palette.gray_blue })
      vim.api.nvim_set_hl(0, "@inclue.python", { fg = palette.gray_blue })
    end
```

**Comment by aktersnurra** [comment]
Yeah, if you want to modify the colorscheme for different languages, I would suggest to fork it (maybe you did that already) and add different highlight groups for each language. It should be fairly obvious how to extend the colorscheme to do this.
