### ISSUE TITLE
Treesitter breaking changes

### ISSUE THREAD

**Issue by smartinellimarco** [aktersnurra/no-clown-fiesta.nvim#34]
New TS version breaks some of the highlight groups.
- [Changes](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0)
- [New highlight groups](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights)

**Comment by aktersnurra** [comment]
Thanks, I'll fix this later today.

**Comment by aktersnurra** [comment]
I [updated](e35c7f984bb278024bc81c6a2fd5fe16a463cab1) it now, but I see that I am missing some capture names, but I will solve this later on.

**Comment by smartinellimarco** [comment]
The only small detail I see so far, are the NOTE, TODO and FIXME comments without color

> I [updated](https://github.com/aktersnurra/no-clown-fiesta.nvim/commit/e35c7f984bb278024bc81c6a2fd5fe16a463cab1) it now, but I see that I am missing some capture names, but I will add those later on. Let me know if you still experience any issues.

**Comment by aktersnurra** [comment]
> The only small detail I see so far, is the NOTE, TODO and FIXME comments without color
> 
> > I [updated](https://github.com/aktersnurra/no-clown-fiesta.nvim/commit/e35c7f984bb278024bc81c6a2fd5fe16a463cab1) it now, but I see that I am missing some capture names, but I will add those later on. Let me know if you still experience any issues.

Fixed it!
