### ISSUE TITLE
Option to change matching Parenthesis/Brackets behavior

### ISSUE THREAD

**Issue by dot-1q** [aktersnurra/no-clown-fiesta.nvim#36]
First of all, really good job on the theme, it is truly fantastic and so easy on the eyes.

Second, this is not really an issue per se, but rather a question I have regarding matching parenthesis and brackets.
I'm not really familiar with Lua, nor how to configure the various neovim behaviors, and I wanted to change the default colors on the matching parenthesis, and the best I could come up with was via:

```
palette = require 'no-clown-fiesta palette'
vim.api.nvim_set_hI(0, 'MatchParen', { underline = false, bold = true, fg = palette.orange })
```
<img width="767" alt="ss" src="https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/30477293/87ee90b5-53e2-4b9b-8aee-bfcda78007f4">

I'm guessing this is the only way, since [this parameter](https://github.com/aktersnurra/no-clown-fiesta.nvim/blob/667d51fd990d52f7ba80d9f76baa217dd79c6b11/lua/no-clown-fiesta/groups/highlights.lua#L63) doesnt have an `options` argument.
Could this be added, or is there a way to configure this that is going over my head completely?

**Comment by aktersnurra** [comment]
Thank you! It is possible, I'll fix it straight away. The new option will be configured like this:

```lua
plugin.setup {
  match_paren = { fg = palette.blue, bg = palette.bg, underline = true } -- default config
}
```
