### ISSUE TITLE
Wrong background for Lazy.nvim floating window

### ISSUE THREAD

**Issue by smartinellimarco** [aktersnurra/no-clown-fiesta.nvim#37]
The background used to be gray as the rest of the screen
<img width="1582" alt="Screenshot 2024-05-05 at 21 03 49" src="https://github.com/aktersnurra/no-clown-fiesta.nvim/assets/15314838/f798c822-415d-4ab8-a98e-0f678352ee70">

**Comment by aktersnurra** [comment]
Just set the backdrop opt in lazy to 100, like so:

```lua
{
  ui = {
    -- The backdrop opacity. 0 is fully opaque, 100 is fully transparent.
    backdrop = 100,
}
```
