### ISSUE TITLE
New pop up menu highlights

### ISSUE THREAD

**Issue by smartinellimarco** [aktersnurra/no-clown-fiesta.nvim#41]
https://www.reddit.com/r/neovim/comments/1f439w8/psa_for_color_scheme_authors_you_might_want_to/

**Comment by aktersnurra** [comment]
Thanks! I will try this out and merge if everything is looks fine.

**Comment by aktersnurra** [comment]
I experimented with the hl groups a bit, but did not notice much difference (except that I changed the bg color). Maybe I do not take full advantage of this options, so this change does not effect this color scheme atm.
