### ISSUE TITLE
Issues when installing with AstroNvim and Packer in Windows 10.

### ISSUE THREAD

**Issue by ChrisMGeo** [aktersnurra/no-clown-fiesta.nvim#6]
I'm using Windows 10 and AstroNvim which uses Packer to install plugins. While there is nothing wrong when installing `no-clown-fiesta.nvim` and there is indeed a colorscheme with the name `no-clown-fiesta`, it doesn't do anything using it through `:colorscheme no-clown-fiesta` results in no change or causes the colorcheme to change into one of neovims defaults.
I use the following command in the init.lua of AstroNvim:
```lua
plugins = {
  init = {
    -- Other plugins
    { "aktersnurra/no-clown-fiesta.nvim" },
  }
}
```

**Comment by aktersnurra** [comment]
I did some refactoring a while back, so instead of using `:colorscheme no-clown-fiesta` it is loaded as any other plugin, i.e. `require("no-clown-fiesta").setup({})`. Could you try that and see if it works?

**Comment by ChrisMGeo** [comment]
Interesting, using it via `:lua require("no-clown-fiesta").setup({})` works but not via the astronvim `init.lua` config file.

**Comment by ChrisMGeo** [comment]
I'll close the issue, it's definitely not something wrong with the theme so far. Keep up the work it's a great theme.

**Comment by aktersnurra** [comment]
Tyvm! 

Try comment out:
```
  "core.bootstrap",
```
seems like his bootstrap only sets the colorscheme. But since the plugins are loaded after, it should not matter. But I would start there. 
Maybe try: 
```
    setup = {},
    config = function() require "configs.no-clown-fiesta" end,
```
Good luck!
